Update quest instructions for QuestPatcher 2.
burritosoftware/GorillaTag-Modding-Guide pull request #2
Opened 2021-06-07 18:51 UTC by Lauriethefish

QuestPatcher 2 will soon be out, and hopefully it'll make modding easier.
This PR updates all of the instructions to be relevant to QuestPatcher 2.

Separate sections of the quest install guide have also been created, based on if you're on windows, mac or linux.

The cosmetic installations using SideQuest have been swapped to using the QuestPatcher cosmetics menu.
Some warnings that are no longer an issue have been removed, since QuestPatcher now has better warnings.

Please review the changes, some could have issues as this is an early draft.

2021-06-08 00:23 UTC, burritosoftware requested changes
Please make sure to capitalize names properly for consistency and maybe clarify prompts like Windows SmartScreen and the macOS gatekeeper with screenshots so it's better looking and easier to understand :D

2021-06-08 00:23 UTC, burritosoftware commented on docs/user-guide/quest/beginners-guide.md
> +1. Select the assets dropdown on github, and click `QuestPatcher-windows.exe`, then wait for the download to finish.
Proper names are preferred for consistency, in this case please use *GitHub*

2021-06-08 00:23 UTC, burritosoftware commented on docs/user-guide/quest/beginners-guide.md
> +2. Open your downloads folder, and double click the installer.
*Downloads*

2021-06-08 00:23 UTC, burritosoftware commented on docs/user-guide/quest/beginners-guide.md
> +3. It's possible that windows will prevent you from opening the installer, as it is from an unknown source. Just press `More Info` and `Run Anyway`.
*Windows*: also preferred if you can put an image of SmartScreen here :D

2021-06-08 00:23 UTC, burritosoftware commented on docs/user-guide/quest/beginners-guide.md
> +### Mac OS
*macOS*

2021-06-08 00:23 UTC, burritosoftware commented on docs/user-guide/quest/beginners-guide.md
> +!> QuestPatcher should automatically download Java. If you're on an older version of Mac OS, Java might be detected as already installed when it isn't. If you are having trouble patching, manually do
*macOS*

2021-06-08 00:23 UTC, burritosoftware commented on docs/user-guide/quest/beginners-guide.md
> +> Other linux distributions may work, but you may encounter issues.
*Linux*

2021-06-08 06:14 UTC, Lauriethefish commented on docs/user-guide/quest/beginners-guide.md
> +> Other linux distributions may work, but you may encounter issues.
Fixed

2021-06-08 06:14 UTC, Lauriethefish commented on docs/user-guide/quest/beginners-guide.md
> +!> QuestPatcher should automatically download Java. If you're on an older version of Mac OS, Java might be detected as already installed when it isn't. If you are having trouble patching, manually do
Fixed

2021-06-08 06:14 UTC, Lauriethefish commented on docs/user-guide/quest/beginners-guide.md
> +### Mac OS
Fixed

2021-06-08 06:14 UTC, Lauriethefish commented on docs/user-guide/quest/beginners-guide.md
> +3. It's possible that windows will prevent you from opening the installer, as it is from an unknown source. Just press `More Info` and `Run Anyway`.
Will add smartscreen image, if I can convince my PC to show it

2021-06-08 06:15 UTC, Lauriethefish commented on docs/user-guide/quest/beginners-guide.md
> +2. Open your downloads folder, and double click the installer.
Fixed

2021-06-08 06:15 UTC, Lauriethefish commented on docs/user-guide/quest/beginners-guide.md
> +1. Select the assets dropdown on github, and click `QuestPatcher-windows.exe`, then wait for the download to finish.
Fixed

2021-06-08 06:23 UTC, Lauriethefish commented on docs/user-guide/quest/beginners-guide.md
> +3. It's possible that windows will prevent you from opening the installer, as it is from an unknown source. Just press `More Info` and `Run Anyway`.
Added smartscreen image.

2021-06-08 16:59 UTC, burritosoftware requested changes
Please add a macOS gatekeeper screenshot, thanks :)

2021-06-08 19:55 UTC, Lauriethefish commented
Done

2021-06-09 19:26 UTC, burritosoftware approved these changes
Looks good to me, will merge when released

2021-06-12 17:00 UTC, merged